spring:
      data:
          mongodb:
                host: localhost
                port: 27017
                database: mongo_otus
                authentication: none
logging:
      level:
        org.springframework.boot.autoconfigure.logging: INFO
        root: INFO
      pattern:
        console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
        file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
      file: application.log
error:
  message: Name is required!

# list of endpoints:  https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#production-ready-endpoints-exposing-endpoints
management:
  endpoints:
    web:
      exposure:
        include: metrics, health, info, logfile # '*'
    jmx:
      exposure:
        include: info, health # '*'
  endpoint:
    health:
      enabled: true
      show-details: always
    logfile:
      enabled: true

info:
  app:
    name: "Try use actuator"