DROP TABLE IF EXISTS AUTHOR;
DROP TABLE IF EXISTS GENRE;
DROP TABLE IF EXISTS BOOK;
DROP TABLE IF EXISTS BOOK_AUTHOR_REL;
DROP TABLE IF EXISTS BOOK_GENRE_REL;
DROP TABLE IF EXISTS BOOK_COMMENT;

CREATE TABLE AUTHOR (ID INT PRIMARY KEY, NAME VARCHAR(255));
CREATE TABLE GENRE (ID INT PRIMARY KEY, NAME VARCHAR(255));
CREATE TABLE BOOK (ID INT PRIMARY KEY, TITLE VARCHAR(255));
CREATE TABLE BOOK_COMMENT (ID INT PRIMARY KEY, BOOK_ID INT, TEXT VARCHAR(255), CRT$DT DATE );
CREATE TABLE BOOK_AUTHOR_REL (BOOK_ID INT, AUTHOR_ID INT);
CREATE TABLE BOOK_GENRE_REL (BOOK_ID INT, GENRE_ID INT);